from scanner_gen.filemanager import Filemanager
from scanner_gen.gerador_afn import LeitorRegex
from scanner_gen.gerador_afd import Subset_construction

regexs = Filemanager.carregar("scanner_gen/teste.txt")
master = LeitorRegex.get_afn_master(regexs)

afd = Subset_construction.afn_to_afd(master)

afd.visualizar()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      